#!/usr/bin/env python3
"""Populate data/default_icons.yaml from a stock packer/SFX stub.

data/default_icons.yaml ships empty on purpose: default icons differ between
tool versions, and a hash copied from an untrusted source produces a check that
looks authoritative while matching nothing. Generate your own instead.

Typical workflow:

    # 1. get the stock stub from the vendor, unmodified
    #      7zS.sfx / 7zSD.sfx  -> the 7-Zip "extra" package
    #      Default.SFX         -> the WinRAR install directory
    #      makensis output     -> an NSIS installer built with no custom icon
    #      Inno Setup output   -> a script compiled with no SetupIconFile
    # 2. hash its icons
    python tools/hash_icons.py 7zSD.sfx \
        --id 7zip_sfx_default \
        --name "7-Zip SFX default icon" \
        --tool 7zip_sfx \
        --note "7-Zip 24.08 extra package"
    # 3. paste the printed block under `default_icons:` in
    #    data/default_icons.yaml

This tool only reads and hashes resources. It never executes the input.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from peguise import icon_fingerprint  # noqa: E402


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="hash_icons.py",
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument("pe_file", help="the stock stub to fingerprint")
    parser.add_argument("--id", required=True,
                        help="machine key for the default_icons entry")
    parser.add_argument("--name", required=True,
                        help="human-readable name shown in PEguise reports")
    parser.add_argument("--tool", default=None,
                        help="matching id from packer_identities.yaml")
    parser.add_argument("--note", default="",
                        help="provenance note, e.g. the exact tool version")
    parser.add_argument("--largest-only", action="store_true",
                        help="emit only the largest icon rather than every size")
    return parser


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)

    path = Path(args.pe_file)
    if not path.is_file():
        print(f"error: no such file: {path}", file=sys.stderr)
        return 2

    report = icon_fingerprint.fingerprint(path)
    if report.status in ("error", "unavailable"):
        print(f"error: {report.status}: {report.status_reason}", file=sys.stderr)
        return 1
    if not report.icons:
        print(f"error: {path} contains no RT_ICON resources", file=sys.stderr)
        return 1

    icons = report.icons
    if args.largest_only:
        icons = [max(icons, key=lambda i: i.size)]

    print(f"# generated by tools/hash_icons.py from {path.name}", file=sys.stderr)
    print(f"# {len(report.icons)} RT_ICON resource(s), "
          f"{len(report.groups)} RT_GROUP_ICON", file=sys.stderr)

    print(f"  - id: {args.id}")
    print(f"    name: {args.name}")
    if args.tool:
        print(f"    tool: {args.tool}")
    note = args.note or f"extracted from {path.name}"
    print(f"    note: {note}")
    print("    sha256:")
    for icon in icons:
        print(f"      - {icon.sha256}   # id={icon.resource_id} {icon.size} bytes")
    return 0


if __name__ == "__main__":
    sys.exit(main())
